#!/usr/bin/env python3

from pathlib import Path
import subprocess

BLOCKLIST = set([
    # supposed to fail
    "assertions.rs",
    "debug.rs",
    "debug_expand.rs",
    "test_expand_errors.rs",
    "trigger_loops.rs",
    "guide/higher_order_fns.rs",
    # failing because out-of-date
    "state_machines/disk_example.rs",
    "scache/rwlock.rs"
    ])

LIB_ONLY = set([
    "std_test/option_test.rs",
    "std_test/result.rs",
    "std_test/template.rs",
    ])

def main():
    completed = subprocess.run(
        ['find', 'link/', '-type', 'f', '-name', '*.rs', '-printf', '%P\n'],
        stdout=subprocess.PIPE,
        text=True,
        check=True,
    )

    print()
    print('# generated by helpers.py')

    for path in sorted(completed.stdout.splitlines()):
        if path in BLOCKLIST:
            continue

        structured_path = Path(path)
        name = '-'.join((structured_path.parent / structured_path.stem).parts)

        print()
        print('[[example]]')
        print(f'name = "{name}"')
        print(f'path = "link/{path}"')

        if path in LIB_ONLY:
            print('crate-type = ["lib"]')

if __name__ == '__main__':
    main()
