[package]
name = "doubly-linked-xor"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
vstd = { path = "../../../vstd" }
builtin = { path = "../../../builtin" }
builtin_macros = { path = "../../../builtin_macros" }

[package.metadata.verus]
verify = true
